### ISSUE TITLE
All data acquisition should be moved into the cron directory

### ISSUE THREAD

**Issue by cclauss** [giacomocerquone/UnivaqBot#11]
Today data acquisition for adsu, professors, and student_office are in cron but news is not.

There should be a cron.py or an everything.py script that gathers fresh data for all four data sources.

**Comment by giacomocerquone** [comment]
I divided those three and the news on purpose. There is a difference between the cron jobs and the pulling of news. One is handled by the OS and the other is handled directly by the telegram library we're using. And you have also to consider that the cron jobs run just once every six months.
Plus, when I wrote the cron jobs, I didn't thought much to improve them like you did creating the get soup function because, as I said, they run once in a blue moon, so...

While for the cron.py, yes we could but actually I thought that separating those three files was the most understandable way.

**Comment by cclauss** [comment]
Good answers.... Closing.
